spring.application.name=OrderService
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${DB_USERNAME:pethumjeewantha}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8080}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
