spring.application.name=OrderService
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${DB_USERNAME:pethumjeewantha}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8080}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

rabbitmq.exchange.name=${RABBITMQ_EXCHANGE:order.exchange}
rabbitmq.queue.order.created=${RABBITMQ_QUEUE_ORDER_CREATED:order.created.queue}
rabbitmq.routing.key.order.created=${RABBITMQ_ROUTING_KEY_ORDER_CREATED:order.created}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
